name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3
          bundler: 1
          bundler-cache: true

      - name: Install
        run: |
          bundle install
